# ------------------------------------------------------------------------------
# AMD drivers
# ------------------------------------------------------------------------------
function install_amd_drivers {
  whiptail --msgbox "Not yet :-(" $WT_HEIGHT $WT_WIDTH

  # Installation manual
  # https://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Install.aspx
  
  # downlaod the driver
  # wget https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-17.10-450821.tar.xz
  
  # extract it
  tar xf amdgpu-pro-17.10-450821.tar.xz

  # run the installer
  ./amdgpu-pro-17.10-450821/amdgpu-pro-install

  # move drivers in the right places
  # https://community.amd.com/message/2769317
  ln -s /opt/amdgpu-pro/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so /usr/lib/x86_64-linux-gnu/dri/amdgpu_drv_video.so
  cp /opt/amdgpu-pro/lib/x86_64-linux-gnu/vdpau/*.* /usr/lib/x86_64-linux-gnu/vdpau/

  # TODO: possibly necessary (https://forum.ubuntuusers.de/topic/amd-athlon-5350-apu-und-radeon-treiber/)
  # dpkg-reconfigure xserver-xorg
  # update-initramfs -u -k all

  usermod -a -G video tooloop
}

# ------------------------------------------------------------------------------
# Nvidia drivers
# ------------------------------------------------------------------------------
function install_nvidia_drivers {
  whiptail --msgbox "Not yet :-(" $WT_HEIGHT $WT_WIDTH

  NVIDIA_VERSION="384.111"
  # TODO: figure out how to withstand exiting xorg and rebooting in the installer...

#   # ------------------------------------------------------------------------------
#   # Exit X11
#   # ------------------------------------------------------------------------------
#   openbox --exit

#   # stop x11 from starting after reboot
#   sed -i '/startx/c\# startx -- -keeptty -nolisten tcp > ~/.xorg.log 2>&1.' /home/tooloop/.bashrc

#   # Disable Nouveau
#   cat >/etc/modprobe.d/nvidia-installer-disable-nouveau.conf <<EOF
# # generated by nvidia-installer
# blacklist nouveau
# options nouveau modeset=0
# EOF

#   update-initramfs -u


#   # ------------------------------------------------------------------------------
#   # Download installer and run it
#   # ------------------------------------------------------------------------------

#   wget http://us.download.nvidia.com/XFree86/Linux-x86_64/${NVIDIA_VERSION}/NVIDIA-Linux-x86_64-${NVIDIA_VERSION}.run
#   chmod +x NVIDIA-Linux-x86_64-${NVIDIA_VERSION}.run


#   # TODO: place in .bashrc
#   ./NVIDIA-Linux-x86_64-${NVIDIA_VERSION}.run

#   # repair link so we can compile GL stuff
#   cd /usr/lib
#   ln -s libGL.so.1 libGL.so 

#   # TODO: add NVIDIA settings to desktop menu

#   reboot
}








# ------------------------------------------------------------------------------
# Processing
# ------------------------------------------------------------------------------
function install_processing {
  PROCESSING_VERSION="3.3.6"
  # Download Processing for Linux 64-bit
  wget --no-check-certificate http://download.processing.org/processing-${PROCESSING_VERSION}-linux64.tgz
  # Unpack the downloaded package to the `/assets` drive
  tar xvzf processing-${PROCESSING_VERSION}-linux64.tgz
  mv processing-${PROCESSING_VERSION} /assets/presentation
  rm xvzf processing-${PROCESSING_VERSION}-linux64.tgz
}